package net.glasslauncher.legacy.jsontemplate;

import com.google.gson.annotations.SerializedName;
import lombok.Getter;
import lombok.Setter;
import net.glasslauncher.common.JsonConfig;

@Getter @Setter
public class LauncherConfig extends JsonConfig {

    /**
     * Last used instance in the dropdown. Only updates when minecraft launches successfully.
     */
    @SerializedName("lastusedinstance")
    private String lastUsedInstance = "";

    /**
     * The last used email in the username box when logging in.
     * This will be a username if the account is MS, so don't assume the contents are a working email.
     */
    @SerializedName("lastusedemail")
    private String lastUsedEmail = "";

    /**
     * A random UUID that is generated by the launcher on first login. If changed, the user will have to log in again if using a Mojang account.
     */
    @SerializedName("clienttoken")
    private String clientToken = "";

    /**
     * If true, treats current user token as an MS token, and validates it using MS servers instead.
     * MS tokens DO work for online-mode play, provided online fixes are installed.
     */
    @SerializedName("ismstoken")
    private boolean isMSToken = false;

    /**
     * Hides the MS login button on both the main launcher window, and the new instance account validation window.
     */
    @SerializedName("ishidingmsbutton")
    private boolean isHidingMSButton = false;

    /**
     * If true, makes all windows use a white system theme where it makes sense.
     */
    @SerializedName("isthemedisabled")
    private boolean isThemeDisabled = false;

    /**
     * Contains the user's session token and in-game username.
     * See lastUsedEmail for the user's login details.
     */
    @SerializedName("logininfo")
    private LoginInfo loginInfo = null;

    /**
     * If true, makes the mod repo tab not filter to your instance version.
     */
    @SerializedName("ignoreinstanceversion")
    private boolean ignoreInstanceVersion = false;

    /**
     * The port which the built-in proxy runs on.
     */
    @SerializedName("proxyport")
    private String proxyPort = "25560";

    /**
     * The port which the built-in webserver for the proxy runs on.
     */
    @SerializedName("webport")
    private String webPort = "25561";

    /**
     * The address which the built-in proxy and webserver runs on.
     */
    @SerializedName("proxyaddress")
    private String proxyAddress = "127.0.0.1";

    public LauncherConfig(String path) {
        super(path);
    }

    /**
     * Sets login info for the user. Saves config when called.
     * Assumes provided loginInfo is Mojang.
     * @param loginInfo
     */
    public void setLoginInfo(LoginInfo loginInfo) {
        setLoginInfo(loginInfo, false);
    }

    /**
     * Sets login info for the user. Saves config when called.
     * @param loginInfo
     * @param isMSToken
     */
    public void setLoginInfo(LoginInfo loginInfo, boolean isMSToken) {
        this.isMSToken = isMSToken;
        this.loginInfo = loginInfo;
        saveFile();
    }

    public String getProxyPort() {
        return proxyPort != null? proxyPort : "25560";
    }

    public String getWebPort() {
        return webPort != null? webPort : "25561";
    }

    public String getProxyAddress() {
        return proxyAddress != null? proxyAddress : "127.0.0.1";
    }
}
